module Repo.RepoIssues exposing (Edges, Input, Issue, Issues, Issues_Edges, Label, Labels, RepoIssues, Repository, input, query)

{-| 
This file is generated from src/Repo.graphql using `elm-gql`

Please avoid modifying directly.

This file can be regenerated by running `elm-gql`



@docs input

@docs Input

@docs RepoIssues

@docs query

@docs Label, Edges, Labels, Issue, Issues_Edges, Issues, Repository


-}


import GitHub
import GitHub.Enum.IssueState
import GitHub.Enum.LockReason
import GraphQL.Engine
import Json.Decode
import Json.Encode
import Scalar


input :
    { states : List GitHub.Enum.IssueState.IssueState
    , issueCount : Int
    , repoName : String
    , repoOwner : String
    }
    -> Input
input args =
    { states = args.states
    , issueCount = args.issueCount
    , repoName = args.repoName
    , repoOwner = args.repoOwner
    }


type alias Input =
    { states : List GitHub.Enum.IssueState.IssueState
    , issueCount : Int
    , repoName : String
    , repoOwner : String
    }


query : Input -> GitHub.Query RepoIssues
query args =
    GraphQL.Engine.bakeToSelection
        (Just "RepoIssues")
        (\version_ ->
            ( GraphQL.Engine.inputObjectToFieldList
                (GraphQL.Engine.inputObject "Input"
                    |> GraphQL.Engine.addField
                        "states"
                        "[IssueState!]!"
                        (Json.Encode.list
                            GitHub.Enum.IssueState.encode
                            args.states
                        )
                    |> GraphQL.Engine.addField
                        "issueCount"
                        "Int!"
                        (Json.Encode.int args.issueCount)
                    |> GraphQL.Engine.addField
                        "repoName"
                        "String!"
                        (Json.Encode.string args.repoName)
                    |> GraphQL.Engine.addField
                        "repoOwner"
                        "String!"
                        (Json.Encode.string args.repoOwner)
                )
            , toPayload_ version_
            )
        )
        decoder_


{-  Return data  -}


type alias RepoIssues =
    { repository : Maybe Repository }


type alias Repository =
    { issues : Issues }


type alias Issues =
    { edges : Maybe (List (Maybe Issues_Edges)) }


type alias Issues_Edges =
    { node : Maybe Issue }


{-  Fragments  -}


type alias Issue =
    { labels : Maybe Labels
    , activeLockReason : Maybe GitHub.Enum.LockReason.LockReason
    , url : GitHub.Uri
    , title : String
    }


type alias Labels =
    { edges : Maybe (List (Maybe Edges)) }


type alias Edges =
    { label : Maybe Label }


type alias Label =
    { name : String }


fragments_ =
    { issue =
        { decoder =
            \start_ ->
                start_
                    |> GraphQL.Engine.versionedJsonField
                        0
                        "labels"
                        (GraphQL.Engine.decodeNullable
                            (Json.Decode.succeed Labels
                                |> GraphQL.Engine.versionedJsonField
                                    0
                                    "edges"
                                    (GraphQL.Engine.decodeNullable
                                        (Json.Decode.list
                                            (GraphQL.Engine.decodeNullable
                                                (Json.Decode.succeed Edges
                                                    |> GraphQL.Engine.versionedJsonField
                                                        0
                                                        "label"
                                                        (GraphQL.Engine.decodeNullable
                                                            (Json.Decode.succeed
                                                                Label
                                                                |> GraphQL.Engine.versionedJsonField
                                                                    0
                                                                    "name"
                                                                    Json.Decode.string
                                                            )
                                                        )
                                                )
                                            )
                                        )
                                    )
                            )
                        )
                    |> GraphQL.Engine.versionedJsonField
                        0
                        "activeLockReason"
                        (GraphQL.Engine.decodeNullable
                            GitHub.Enum.LockReason.decoder
                        )
                    |> GraphQL.Engine.versionedJsonField
                        0
                        "url"
                        Scalar.uri.decoder
                    |> GraphQL.Engine.versionedJsonField
                        0
                        "title"
                        Json.Decode.string
        }
    }


decoder_ : Int -> Json.Decode.Decoder RepoIssues
decoder_ version_ =
    Json.Decode.succeed RepoIssues
        |> GraphQL.Engine.versionedJsonField
            version_
            "repository"
            (GraphQL.Engine.decodeNullable
                (Json.Decode.succeed Repository
                    |> GraphQL.Engine.versionedJsonField
                        0
                        "issues"
                        (Json.Decode.succeed Issues
                            |> GraphQL.Engine.versionedJsonField
                                0
                                "edges"
                                (GraphQL.Engine.decodeNullable
                                    (Json.Decode.list
                                        (GraphQL.Engine.decodeNullable
                                            (Json.Decode.succeed Issues_Edges
                                                |> GraphQL.Engine.versionedJsonField
                                                    0
                                                    "node"
                                                    (GraphQL.Engine.decodeNullable
                                                        (Json.Decode.succeed
                                                            Issue
                                                            |> fragments_.issue.decoder
                                                        )
                                                    )
                                            )
                                        )
                                    )
                                )
                        )
                )
            )


toPayload_ : Int -> String
toPayload_ version_ =
    (((((((((GraphQL.Engine.versionedAlias version_ "repository" ++ " (name: ")
                ++ GraphQL.Engine.versionedName version_ "$repoName"
           )
            ++ ", owner: "
          )
            ++ GraphQL.Engine.versionedName version_ "$repoOwner"
         )
            ++ ") {issues (states: "
        )
            ++ GraphQL.Engine.versionedName version_ "$states"
       )
        ++ ", last: "
      )
        ++ GraphQL.Engine.versionedName version_ "$issueCount"
     )
        ++ """) {edges {node {
...Issue } } } }"""
    )
        ++ """fragment Issue on Issue { {title
url
activeLockReason
labels(first: 5) {edges {label: node {name}}}} }"""


