module GitHub exposing (Base64String(..), Date(..), DateTime(..), GitObjectID(..), GitSSHRemote(..), GitTimestamp(..), Html(..), Id(..), Mutation, Option, PreciseDateTime(..), Query, Uri(..), X509certificate(..), absent, base64String, batch, date, dateTime, gitObjectID, gitSSHRemote, gitTimestamp, html, id, map, map2, mutation, null, preciseDateTime, present, query, uri, x509certificate)

{-| 
This is a file generated by `elm-gql` when you ran `elm-gql init`!

It's yours now to do whatever you want with.

This file does include decoders and encoders for all the Scalars for your GQL endpoint.  You'll need to make sure they are implemented correctly.

## Queries

@docs query, Query

## Mutations

@docs mutation, Mutation

## Optional Inputs

@docs Option, present, absent, null

## Batching and Mapping

@docs map2, map, batch

## Scalar Decoders and Encoders

@docs x509certificate, X509certificate, uri, Uri, preciseDateTime, PreciseDateTime, id, Id, html, Html, gitTimestamp, GitTimestamp, gitSSHRemote, GitSSHRemote, gitObjectID, GitObjectID, dateTime, DateTime, date, Date, base64String, Base64String
-}


import GraphQL.Engine
import Http
import Json.Decode
import Json.Encode


type alias Query data =
    GraphQL.Engine.Selection GraphQL.Engine.Query data


type alias Mutation data =
    GraphQL.Engine.Selection GraphQL.Engine.Mutation data


type alias Selection source data =
    GraphQL.Engine.Selection source data


query :
    Query data
    -> { headers : List Http.Header
    , url : String
    , timeout : Maybe Float
    , tracker : Maybe String
    }
    -> Cmd (Result GraphQL.Engine.Error data)
query sel options =
    GraphQL.Engine.query sel options


mutation :
    Mutation data
    -> { headers : List Http.Header
    , url : String
    , timeout : Maybe Float
    , tracker : Maybe String
    }
    -> Cmd (Result GraphQL.Engine.Error data)
mutation sel options =
    GraphQL.Engine.mutation sel options


null : Option value
null =
    GraphQL.Engine.Null


absent : Option value
absent =
    GraphQL.Engine.Absent


present : input -> Option input
present input =
    GraphQL.Engine.Present input


type alias Option input =
    GraphQL.Engine.Option input


batch : List (Selection source data) -> Selection source (List data)
batch =
    GraphQL.Engine.batch


map : (a -> b) -> Selection source a -> Selection source b
map =
    GraphQL.Engine.map


map2 :
    (a -> b -> c)
    -> Selection source a
    -> Selection source b
    -> Selection source c
map2 =
    GraphQL.Engine.map2


type alias Codec scalar =
    { encode : scalar -> Json.Encode.Value
    , decoder : Json.Decode.Decoder scalar
    }


type Base64String
    = Base64String String


base64String : Codec Base64String
base64String =
    { encode =
        \val ->
            case val of
                Base64String str ->
                    Json.Encode.string str
    , decoder = Json.Decode.map Base64String Json.Decode.string
    }


type Date
    = Date String


date : Codec Date
date =
    { encode =
        \val ->
            case val of
                Date str ->
                    Json.Encode.string str
    , decoder = Json.Decode.map Date Json.Decode.string
    }


type DateTime
    = DateTime String


dateTime : Codec DateTime
dateTime =
    { encode =
        \val ->
            case val of
                DateTime str ->
                    Json.Encode.string str
    , decoder = Json.Decode.map DateTime Json.Decode.string
    }


type GitObjectID
    = GitObjectID String


gitObjectID : Codec GitObjectID
gitObjectID =
    { encode =
        \val ->
            case val of
                GitObjectID str ->
                    Json.Encode.string str
    , decoder = Json.Decode.map GitObjectID Json.Decode.string
    }


type GitSSHRemote
    = GitSSHRemote String


gitSSHRemote : Codec GitSSHRemote
gitSSHRemote =
    { encode =
        \val ->
            case val of
                GitSSHRemote str ->
                    Json.Encode.string str
    , decoder = Json.Decode.map GitSSHRemote Json.Decode.string
    }


type GitTimestamp
    = GitTimestamp String


gitTimestamp : Codec GitTimestamp
gitTimestamp =
    { encode =
        \val ->
            case val of
                GitTimestamp str ->
                    Json.Encode.string str
    , decoder = Json.Decode.map GitTimestamp Json.Decode.string
    }


type Html
    = Html String


html : Codec Html
html =
    { encode =
        \val ->
            case val of
                Html str ->
                    Json.Encode.string str
    , decoder = Json.Decode.map Html Json.Decode.string
    }


type Id
    = Id String


id : Codec Id
id =
    { encode =
        \val ->
            case val of
                Id str ->
                    Json.Encode.string str
    , decoder = Json.Decode.map Id Json.Decode.string
    }


type PreciseDateTime
    = PreciseDateTime String


preciseDateTime : Codec PreciseDateTime
preciseDateTime =
    { encode =
        \val ->
            case val of
                PreciseDateTime str ->
                    Json.Encode.string str
    , decoder = Json.Decode.map PreciseDateTime Json.Decode.string
    }


type Uri
    = Uri String


uri : Codec Uri
uri =
    { encode =
        \val ->
            case val of
                Uri str ->
                    Json.Encode.string str
    , decoder = Json.Decode.map Uri Json.Decode.string
    }


type X509certificate
    = X509certificate String


x509certificate : Codec X509certificate
x509certificate =
    { encode =
        \val ->
            case val of
                X509certificate str ->
                    Json.Encode.string str
    , decoder = Json.Decode.map X509certificate Json.Decode.string
    }


